### ISSUE TITLE
Harvest metadata from CORDIS

### ISSUE THREAD

**Issue by roblokers** [soilwise-he/harvesters#17]
cordis offers a SPARQL endpoint which is able to extract deliverables (reports, articles, datasets, tools) from from research projects. In theory research projects can be identified by their funding scheme, however we nitoced the fundingscheme property of the projects is usually not populated

some sample sparql queries to cordis are documented at https://git.wur.nl/isric/soilwise/soilwise-docs/-/wikis/Cordis-SPARQL-Query:-Projects-with-%22Soil%22-as-part-of-the-abstract-Access-to-Datasets-and-Project-Publications (internal)

DoD
- [x] setup API read access to CORDIS infrastructure
- [x] process CORDIS RDF 
- [x] store results in the common SWR metadata schema (PostgreSQL)
- [x] make CORDIS metadata available through the catalogue

**Comment by pvgenuchten** [comment]
Move harvester to ci-cd

See also https://github.com/soilwise-he/harvesters/issues/22

**Comment by roblokers** [comment]
We need to change this into a task that operationalizes the harvesting of all sources

**Comment by roblokers** [comment]
> The name, description and DoD are a bit conflicting here. Where we have separate tickets on developing the harvesting process for different sources, this one seems to focus on the operationalisation of the processes. We probably need add a (generic) task that operationalizes the harvesting of all sources and change the DoD for this ticket

Done that 
- new issue for operationalisation https://github.com/soilwise-he/harvesters/issues/34
- updated DoD of this ticket (but other harvesting tickets to be checked)
