### ISSUE TITLE
Harvest metadata from Zenodo

### ISSUE THREAD

**Issue by roblokers** [soilwise-he/harvesters#18]
zenodo has an oai-pmh interface, which can be harvested by oai-pmh aware software

however we have noticed the zenodo api provides more options on metadata model and filtering, which makes it a more preferable option, the risk is that we have to develop dedicates harvesters for individual platforms

**Comment by pvgenuchten** [comment]
direct harvesting of zenodo seems irrelavant to the project, as explained in https://github.com/soilwise-he/governance/issues/8
