### ISSUE TITLE
harvester sources database

### ISSUE THREAD

**Issue by pvgenuchten** [soilwise-he/harvesters#22]
initial work indicates that harvester sources can best be stored in a postgres database, prior to loading them in the triple store

some of the cleaning (deduplication, translation, augmentation) can best be managed in the database

this task aims to set up a harvester-sources database and routines to populate it from harvesters, and export it to triple store

```mermaid
flowchart LR
    A[Cordis] -->|SPARQL| HS(Harvester sources)
    B[OpenAire] -->|DOI| HS
    c[Bonares] -->|CSW| HS
    HS --> MH(Harmonised)
    MA[Augmentation] --> MH
    MH --> MA
    MH --> Catalogue
    MH --> 3S[Triple Store]
    MH --> LLM
```

DoD

- [x] Database schema
- [x] Created database
- [x] Harvest Cordis to database
- [x] Augment DOI's from CORDIS from OpenAire (and crossref.org?)
- [x] Harvest Bonares to database
- [x] Merge records from various sources to harmonised database
- [x] Export metadata to triple store
- [x] Optimise metadata to fit pycsw expectations

**Comment by pvgenuchten** [comment]
Metadata harvests run as CI-CD tasks using [owslib](https://github.com/geopython/owslib), [oaiharvest](https://pypi.org/project/oaiharvest) or sparql

**Comment by BerkvensNick** [comment]
@hugodegrootwurnl , do you know if the following aspects have been 'done'?:

- [ ] Merge records from various sources to harmonised database
- [ ] Export metadata to triple store
- [ ] Optimise metadata to fit pycsw expectations

**Comment by roblokers** [comment]
> @hugodegrootwurnl , do you know if the following aspects have been 'done'?:
> 
> * [ ]  Merge records from various sources to harmonised database
> * [ ]  Export metadata to triple store
> * [ ]  Optimise metadata to fit pycsw expectations

Still ongoing
