### ISSUE TITLE
harvest Bonares repository

### ISSUE THREAD

**Issue by pvgenuchten** [soilwise-he/harvesters#3]
the [Bonares](https://www.bonares.de/research-data) facility, operated by ZALF, on behalf of the German federal ministery of education and research, maintains a repository of LTE networks in Europe, which provide a number of interesting datasets on soil health indicators.

[The catalogue](https://maps.bonares.de/mapapps/resources/apps/bonares) is an interactive map with a tailored rest api

However there is also sitemap.xml with links to records encoded as iso19139:2007
https://maps.bonares.de/finder/resources/googleds/sitemap.xml

There is a CSW service via <https://maps.bonares.de/soapServices/services/CSWDiscovery>

The contents of the catalogue includes BGR and [edaphobase](https://portal.edaphobase.org) 

Bonares also maintains a dataset of Soil profiles in Germany.

DoD:

- [x] container to run harvest
- [x] set up ci-cd to run harvest

**Comment by cdonmez16** [comment]
Yes, the CSW service should be active for data discovery and retrieval. Additionally, we may offer further options to adopt automated harvesting for the SWR. I will get back to you as soon as possible. Next week's architecture meeting will also provide a good basis for further detailed discussion. @pvgenuchten

**Comment by pvgenuchten** [comment]
Move the harvester from ejpsoil-approach to soilwise approach

- see also https://github.com/soilwise-he/harvesters/issues/22
