### ISSUE TITLE
Keywords for filtering harvested data

### ISSUE THREAD

**Issue by cdonmez16** [soilwise-he/harvesters#33]
A substantial dataset from existing repositories such as BonaRes and Zenodo has been compiled, encompassing a broad spectrum of soil research information. The demo already features a basic search function that includes country-based filtering. To enhance user experience further and help users efficiently locate relevant data through the SW, we need to implement an advanced search function—such as pop-ups or tickboxes—that allows for keyword-based filtering.

To support this development, within our tasks in WP2-WP3, we have conducted a thorough literature review, screening around 170 research papers (mainly WOS and Scopus based) to identify relevant keywords associated with data reuse in various fields (agriculture, environment, soil). The list of these keywords is attached.

[SWdata_catalogue_filtering_Cenk.docx](https://github.com/user-attachments/files/16440514/SWdata_catalogue_filtering_Cenk.docx)

@pvgenuchten @roblokers   Is such information relevant at this stage? Shall we discuss it further to improve/specify? The document comprises only the outputs. I can share the details of the study in a respective deliverable.

**Comment by roblokers** [comment]
Definitely useful and good to follow up . Also good to take the JRC taxonomy for soil degradation into account as specified in EUSO and documented here: https://github.com/soilwise-he/SoilWise-documentation/blob/main/tech/docs/technical_components/metadata_augmentation.md

**Comment by pvgenuchten** [comment]
we're collecting activities related to vocabularies in https://github.com/soilwise-he/soilwise-ontology/blob/main/docs/terminology.md. I will add this initiative there?

**Comment by pvgenuchten** [comment]
these facets are now used in the latest prototype
