### ISSUE TITLE
fetch content from openaire if any doi is imported from elsewhere

### ISSUE THREAD

**Issue by pvgenuchten** [soilwise-he/harvesters#35]
doi's are imported from various locations, esdac, bonares, cordis
openaire may be able to extend the information about these dois
a process should fetch dois from the database which have not already been retrieved previously

- query the database for doi's which are not already retrieved previously (even if not present in openaire)
- for those doi's fecth openaire information
- store the information indicating the doi is in openaire (so both records can be augmented)
- if the doi is not in openaire? -> look in alternate platforms/or mark the doi as `not in openaire`, so the query is not repeatd in next iteration

**Comment by hugodegrootwurnl** [comment]
The number of DOIS that are not in openaire is decreasing. DOIs that are not in openaire should be queried in the next iteration, as they might have been added there in the meantime. It turned out many of them did. so I skipped the fourth bullet.
