### ISSUE TITLE
harvest submitted reports from Cordis which have no DOI

### ISSUE THREAD

**Issue by pvgenuchten** [soilwise-he/harvesters#58]
Seems current cordis harvester selects only resources which have a DOI.

Intent of this task is to extend the mechanism to also include project deliverables which have no assigned DOI

- [x] Understand from the cordis knowledge graph, if it includes the url of the document
- [x] Understand if Soilwise is willing to include resources which are not identified by a DOI, if not, we can exclude all resources without persistent identification.
- [ ] Include the (minimal) metadata of the document
- [ ] Understand if Soilwise is interested to augment the metadata from context (project coordinator, author info in the actual document, document content (NLP), etc)

**Comment by hugodegrootwurnl** [comment]
On 'Understand from the cordis knowledge graph, if it includes the url of the document': there are many items which link to some sort of download. Often deliverables of EU projects - can be anything, with our without valuable content. It even can be a zip-file with all kind of contents. With no metadata.

SPARQL query at CORDIS for non DOIs:

```
PREFIX eurio:<http://data.europa.eu/s66#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX ns: <http://example.com/namespace>
SELECT ?result ?url ?title
WHERE
{
  ?project a eurio:Project.
  ?project eurio:abstract ?abstract.
  ?project eurio:hasResult ?result.
  ?result eurio:title ?title.
  ?result eurio:url ?url.
  optional { ?result eurio:doi ?doi }.
  FILTER ( coalesce(?doi,'') = '' )
  FILTER regex(?abstract, "Soil", "i")
}
```

The part that filters on 'not having a DOI':
```
  optional { ?result eurio:doi ?doi }.
  FILTER ( coalesce(?doi,'') = '' )
```

For the zip example add one extra FILTER element to the SPARQL query:

`  FILTER regex(?title, "UEB fluxes", "i")`

Result:
https://ec.europa.eu/research/participants/documents/downloadPublic?documentIds=080166e5b7f451e3&appId=PPGMS

And finally an example of one of the many results with questionable value (title='Brand Image'): 
`  FILTER regex(?title, "Brand Image", "i")`

Result:
https://ec.europa.eu/research/participants/documents/downloadPublic?documentIds=080166e5ba6019d5&appId=PPGMS

**Comment by hugodegrootwurnl** [comment]
Rob Lokers and I had a look at the non-doi items. It seems they are all about reporting project deliverables and project progress. And on first glace NOT useful for the project.

So tasks 3 and 4 of this issue are no longer relevant
